"""
Strict Pydantic schemas for API request/response validation
and structured AI output parsing.
"""

from pydantic import BaseModel, Field
from typing import List, Optional
from uuid import UUID
from datetime import datetime


# ═══════════════════════════════════════════════════
# AI Structured Output Schemas
# ═══════════════════════════════════════════════════

class JDAnalysisSchema(BaseModel):
    """Parsed output from JD analysis by Groq llama3-70b."""
    job_title: str = Field(..., description="Extracted job title")
    salary_range: Optional[str] = Field(None, description="Salary range if mentioned; None triggers quality alert")
    must_have_skills: List[str] = Field(default_factory=list, description="Must-have skills; <3 triggers quality alert")
    nice_to_have_skills: List[str] = Field(default_factory=list, description="Nice-to-have skills")
    years_of_experience: int = Field(0, description="Required years of experience")
    location: Optional[str] = Field(None, description="Job location if specified")
    job_type: Optional[str] = Field(None, description="Full-time, Part-time, Contract, etc.")


class CVExtractionSchema(BaseModel):
    """Parsed output from CV extraction by Groq llama3-70b."""
    candidate_name: str = Field(..., description="Full name of the candidate")
    candidate_email: str = Field(..., description="Email address")
    total_years_experience: int = Field(0, description="Total years of professional experience")
    tech_stack: List[str] = Field(default_factory=list, description="Technical skills and technologies")
    recent_projects_summary: str = Field("", description="Summary of recent/notable projects")


class InterviewBlueprintSchema(BaseModel):
    """Interview plan generated by Groq llama3-70b."""
    total_questions: int = Field(default=5, ge=3, le=5, description="Number of STAR-method questions (always 5)")
    first_question: str = Field(..., description="First behavioral STAR-format question")


class InterestScoreEvaluationSchema(BaseModel):
    """Per-answer interest score from the background worker."""
    interest_score: int = Field(..., ge=0, le=100, description="Interest/enthusiasm score 0-100")
    reasoning: str = Field(..., max_length=500, description="Max 2 sentences explaining the score")
    signals: dict = Field(default_factory=dict, description="Extracted NLP signals (sentiment, depth, salary, etc.)")


# ═══════════════════════════════════════════════════
# API Request Schemas
# ═══════════════════════════════════════════════════

class JobCreateRequest(BaseModel):
    """Raw JD text submission."""
    raw_text: str = Field(..., min_length=50, description="Raw job description text")


class ApplicationCreateRequest(BaseModel):
    """Application submission with candidate info."""
    job_id: UUID
    candidate_name: str
    candidate_email: str


class AudioSubmissionResponse(BaseModel):
    """Response after processing candidate audio."""
    transcript: str
    next_question: Optional[str] = None
    is_complete: bool = False
    questions_completed: int
    total_questions: int


# ═══════════════════════════════════════════════════
# API Response Schemas
# ═══════════════════════════════════════════════════

class JobResponse(BaseModel):
    id: UUID
    title: str
    raw_text: str
    parsed_params: Optional[dict] = None
    must_haves: Optional[list] = None
    status: str
    created_at: datetime
    updated_at: datetime
    warnings: Optional[List[str]] = None

    model_config = {"from_attributes": True}


class CandidateResponse(BaseModel):
    id: UUID
    name: str
    email: str
    cv_parsed_json: Optional[dict] = None
    created_at: datetime

    model_config = {"from_attributes": True}


class ApplicationResponse(BaseModel):
    id: UUID
    job_id: UUID
    candidate_id: UUID
    match_score: int
    final_interest_score: float
    status: str
    created_at: datetime
    candidate: Optional[CandidateResponse] = None

    model_config = {"from_attributes": True}


class InterviewResponse(BaseModel):
    id: UUID
    application_id: UUID
    total_allocated_questions: int
    questions_completed: int
    status: str
    created_at: datetime

    model_config = {"from_attributes": True}


class InterviewQnAResponse(BaseModel):
    id: UUID
    interview_id: UUID
    q_number: int
    ai_question: str
    candidate_answer: Optional[str] = None
    interest_score: Optional[int] = None
    score_reasoning: Optional[str] = None

    model_config = {"from_attributes": True}


class InterviewStateResponse(BaseModel):
    """Full state sent to candidate frontend."""
    interview_id: UUID
    application_id: UUID
    job_title: str
    candidate_name: str
    current_question: str
    current_q_number: int
    total_questions: int
    status: str  # in_progress | completed


class JDQualityAlert(BaseModel):
    """Returned as HTTP 400 when JD fails quality checks."""
    error: str = "JD_QUALITY_ALERT"
    issues: List[str]
    parsed_data: Optional[JDAnalysisSchema] = None


class HealthResponse(BaseModel):
    status: str = "healthy"
    version: str = "1.0.0"
    service: str = "Project Catalyst API"
